name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -f Dockerfile -t handover/backend-tests .
      - name: Run tests
        run: docker run -v -d handover/backend-tests go test -v ./...
